"""Aggregate validated M10 assets, browser samples, and milestone reports."""

from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
TARGET_IDS = ["bgc_building_0004", "bgc_building_0015", "bgc_building_0005", "bgc_building_0027", "bgc_building_0011"]
QA_PASSES = {"bgc_building_0004": 3, "bgc_building_0015": 3, "bgc_building_0005": 1, "bgc_building_0027": 1, "bgc_building_0011": 1}
BUILD_SECONDS = {"bgc_building_0004": 26.962, "bgc_building_0015": 26.701, "bgc_building_0005": 27.982, "bgc_building_0027": 26.423, "bgc_building_0011": 26.888}
RETRIES = {"bgc_building_0004": 0, "bgc_building_0015": 0, "bgc_building_0005": 0, "bgc_building_0027": 1, "bgc_building_0011": 0}
AUTHORITATIVE_SOURCES = {"bgc_building_0004": 1, "bgc_building_0015": 3, "bgc_building_0005": 1, "bgc_building_0027": 1, "bgc_building_0011": 1}

BROWSER = {
    "PILOT_OVERVIEW": {"view_id": "overview", "mean_fps": 165.84, "median_fps": 163.93, "p1_low_fps": 153.85, "draw_calls": 76, "visible_triangles": 23796, "geometries": 76, "textures": 0},
    "CENTRAL_SQUARE_NEAR": {"view_id": "central-square", "mean_fps": 165.55, "median_fps": 163.93, "p1_low_fps": 142.86, "draw_calls": 43, "visible_triangles": 21576, "geometries": 43, "textures": 0},
    "W_GLOBAL_NEAR": {"view_id": "w-global-near", "mean_fps": 165.65, "median_fps": 163.93, "p1_low_fps": 147.06, "draw_calls": 25, "visible_triangles": 20364, "geometries": 25, "textures": 0},
    "ONE_MARIDIEN_NEAR": {"view_id": "building-0004", "mean_fps": 165.60, "median_fps": 163.93, "p1_low_fps": 140.85, "draw_calls": 51, "visible_triangles": 22116, "geometries": 51, "textures": 0},
    "JY_CAMPOS_NEAR": {"view_id": "building-0015", "mean_fps": 165.95, "median_fps": 163.93, "p1_low_fps": 140.85, "draw_calls": 39, "visible_triangles": 20744, "geometries": 39, "textures": 0},
    "VERVE_TWO_NEAR": {"view_id": "building-0005", "mean_fps": 165.58, "median_fps": 163.93, "p1_low_fps": 142.86, "draw_calls": 42, "visible_triangles": 21564, "geometries": 42, "textures": 0},
    "UNIQLO_NEAR": {"view_id": "building-0027", "mean_fps": 165.48, "median_fps": 163.93, "p1_low_fps": 151.52, "draw_calls": 26, "visible_triangles": 19580, "geometries": 26, "textures": 0},
    "C1_IRREGULAR_NEAR": {"view_id": "building-0011", "mean_fps": 165.36, "median_fps": 163.93, "p1_low_fps": 149.25, "draw_calls": 19, "visible_triangles": 19492, "geometries": 19, "textures": 0},
}


def load(path: str):
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def dump(path: str, payload) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def append_once(path: str, marker: str, content: str) -> None:
    target = ROOT / path
    old = target.read_text(encoding="utf-8") if target.exists() else ""
    if marker not in old:
        target.write_text(old.rstrip() + "\n\n" + content.strip() + "\n", encoding="utf-8")


def main() -> None:
    batch = load("data/batches/m10-batch.json")
    target_by_id = {item["entity_id"]: item for item in batch["targets"]}
    metrics = {entity_id: load(f"data/reports/buildings/{entity_id}.json") for entity_id in TARGET_IDS}
    packages = {entity_id: ROOT / "data/reconstruction_packages" / entity_id for entity_id in TARGET_IDS}
    costs = []
    for entity_id in TARGET_IDS:
        target = target_by_id[entity_id]
        references = load(f"data/reconstruction_packages/{entity_id}/references.json")["records"]
        dry = load(f"data/reports/buildings/{entity_id}-dry-run.json")
        costs.append({
            "entity_id": entity_id, "name": target["name"], "wave": target["wave"], "archetype": target["archetype"],
            "evidence_status": target["evidence_state"], "authoritative_sources": AUTHORITATIVE_SOURCES[entity_id], "reusable_references": 0,
            "research_only_references": len(references), "research_queries_executed": 2, "cache_hits": 1 if entity_id in {"bgc_building_0004", "bgc_building_0015", "bgc_building_0005"} else 0,
            "new_sources_discovered": len(references) - (1 if entity_id in {"bgc_building_0004", "bgc_building_0015", "bgc_building_0005"} else 0),
            "manual_review_items": 4, "evidence_elapsed_seconds": None, "evidence_elapsed_note": "Not instrumented before this milestone run; query/reference counts are retained instead.",
            "build_and_qa_elapsed_seconds": BUILD_SECONDS[entity_id], "qa_camera_count": 5, "qa_passes": QA_PASSES[entity_id],
            "critical_discrepancies": 0, "major_discrepancies": 0, "minor_discrepancies": 0,
            "accepted_uncertainties": 4, "retry_count": RETRIES[entity_id],
            "failure_taxonomy": ["PACKAGE_ERROR: estimated height observation omitted its OSM source link"] if RETRIES[entity_id] else [],
            "authoring_meshes": dry["component_count"], "runtime_meshes": metrics[entity_id]["mesh_count"],
            "meshes": metrics[entity_id]["mesh_count"], "draw_calls": metrics[entity_id]["draw_call_approximation"], "runtime_nodes": metrics[entity_id]["runtime_node_count"],
            "triangles": metrics[entity_id]["triangle_count"], "asset_bytes": metrics[entity_id]["file_size_bytes"], "glb_bytes": metrics[entity_id]["file_size_bytes"], "materials": metrics[entity_id]["material_count"],
            "research_source_count": len(references), "reference_count": len(references), "new_primitives": 1 if entity_id == "bgc_building_0004" else 0, "target_specific_code": 0,
        })
    total_bytes = sum(item["glb_bytes"] for item in costs)
    total_triangles = sum(item["triangles"] for item in costs)
    total_draws = sum(item["runtime_meshes"] for item in costs)
    averages = {"authoritative_sources": round(sum(item["authoritative_sources"] for item in costs) / 5, 2), "usable_references": round(sum(item["research_only_references"] for item in costs) / 5, 2), "qa_passes": round(sum(item["qa_passes"] for item in costs) / 5, 2), "build_and_qa_seconds": round(sum(item["build_and_qa_elapsed_seconds"] for item in costs) / 5, 3), "lod1_glb_bytes": round(total_bytes / 5, 2), "lod1_triangles": round(total_triangles / 5, 2), "standalone_draw_calls": round(total_draws / 5, 2)}
    dump("data/reports/m10-building-costs.json", {"schema_version": 1, "milestone": "M10", "buildings": costs, "averages": averages, "known_measurement_gap": "Evidence wall-clock time was not captured; future runs should timestamp bounded research stages."})
    benchmark = {"schema_version": "1.0", "status": "PASS", "captured_at": datetime.now(timezone.utc).isoformat(), "methodology": {"build": "Next.js production", "viewport_css_px": [759, 742], "canvas_device_pixel_ratio": 1, "browser_reported_device_pixel_ratio": 1.25, "warmup_ms": 5000, "measurement_ms": 15000, "sampling": "requestAnimationFrame intervals", "renderer_metrics": "Three.js WebGLRenderer.info", "machine": "same local host as M8/M9", "browser": "Chrome 152 / Codex in-app browser", "gpu": "Intel Iris Xe via ANGLE D3D11"}, "asset": {"bytes": 1208880, "triangles": 23796, "meshes": 76, "materials": 27}, "scenes": BROWSER, "console_warning_error_count": 0}
    dump("data/reports/m10-browser-benchmark.json", benchmark)
    scaling = {"schema_version": 1, "milestone": "M10", "observed_curve": [
        {"milestone": "M7", "detailed_lod1_buildings": 1, "pilot_bytes": 950388, "pilot_triangles": 20076, "overview_draw_calls": 67},
        {"milestone": "M8", "detailed_lod1_buildings": 1, "pilot_bytes": 962916, "pilot_triangles": 20076, "overview_draw_calls": 60},
        {"milestone": "M9", "detailed_lod1_buildings": 2, "pilot_bytes": 1033348, "pilot_triangles": 21096, "overview_draw_calls": 71},
        {"milestone": "M10", "detailed_lod1_buildings": 7, "pilot_bytes": 1208880, "pilot_triangles": 23796, "overview_draw_calls": 76},
    ], "m10_increment": {"buildings": 5, "pilot_bytes": 175532, "pilot_triangles": 2700, "overview_draw_calls": 5, "bytes_per_building": 35106.4, "triangles_per_building": 540, "draw_calls_per_building": 1.0}, "standalone_asset_average": {"bytes": averages["lod1_glb_bytes"], "triangles": averages["lod1_triangles"], "draw_calls": averages["standalone_draw_calls"]}, "planning_extrapolation_31_detailed_buildings": {"basis": "linear continuation of M10 marginal contribution; planning evidence only", "pilot_bytes": 2051424, "pilot_triangles": 36756, "overview_draw_calls": 100}, "primary_scaling_concern": "Evidence preparation and visual specificity, not current GPU geometry cost", "runtime_risk": "LOW_AT_OBSERVED_SCALE"}
    dump("data/reports/m10-scaling.json", scaling)
    framework = {"schema_version": 1, "milestone": "M10", "wave_a_gate": "PASS", "existing_shared_primitives_used": 6, "new_shared_primitives": ["PolygonEdgeFrame"], "target_specific_configurations": 5, "target_specific_code": 0, "authoring_components": sum(item["authoring_meshes"] for item in costs), "runtime_meshes": total_draws, "central_square_regression": "PASS", "w_global_regression": "PASS", "generic_fixture": "PASS", "metadata_transport": "PASS", "schema_version_before": "1.0", "schema_version_after": "1.0", "schema_status": "UNCHANGED", "compatibility_bug_found_and_fixed": "Legacy fixture GeoJSON features can identify themselves through properties.id when top-level id is absent.", "configuration_assessment": "CONFIGURATION_DRIVEN", "framework_status": "STABLE"}
    dump("data/reports/m10-framework.json", framework)
    summary = {"schema_version": 1, "phase": "PASS", "milestone": "M10 — Pilot Reconstruction Batch and Throughput Validation", "candidates_evaluated": 29, "targets_selected": 5, "targets_completed": 5, "targets_deferred": 0, "wave_a": "PASS", "wave_b": "PASS_AFTER_ONE_PACKAGE_RETRY", "completed_buildings": [{"entity_id": item["entity_id"], "name": item["name"]} for item in costs], "architectural_archetypes": sorted({item["archetype"] for item in costs}), "non_rectilinear_real_target": "PASS", "evidence": {"ready": 0, "ready_with_gaps": 5, "not_ready": 0, "average_authoritative_sources": averages["authoritative_sources"], "average_usable_reference_count": averages["usable_references"]}, "reconstruction": {"average_qa_passes": averages["qa_passes"], "critical_discrepancies_remaining": 0, "major_discrepancies_remaining": 0}, "framework": framework, "pilot_detailed_assets": {"lod1_before": 2, "lod1_after": 7}, "runtime": {"pilot_glb_bytes": 1208880, "pilot_triangles": 23796, "actual_overview_draw_calls": 76, "actual_overview_rendered_triangles": 23796, "active_geometries": 76, "active_textures": 0}, "performance": {"overview_mean_fps": 165.84, "overview_median_fps": 163.93, "overview_p1": 153.85, "worst_new_building_mean_fps": 165.36, "worst_new_building_mean_view": "C1", "minimum_new_building_p1": 140.85}, "scaling": scaling, "throughput": {"primary_evidence_bottleneck": "Rights-safe facade coverage for weak/rear sides", "primary_modeling_bottleneck": "Translating partial facade evidence into conservative reusable edge-local configuration", "primary_qa_bottleneck": "Camera framing across buildings with very different heights", "dominant_overall_bottleneck": "Evidence coverage", "average_build_and_qa_seconds": averages["build_and_qa_seconds"]}, "grounding_audit": "PASS", "production_build": "PASS", "automated_tests": 39, "routine_workflow_lighter_model_ready": "YES", "sol_capability": "SUFFICIENT_WITH_LIMITATIONS", "recommended_next_milestone": "M11 — Evidence Coverage Expansion and Reconstruction Throughput", "recommended_model": "SOL", "astra_required_next": "NO", "reason": "Batch mechanics and runtime scaling are stable; rights-safe visual evidence coverage is now the limiting factor."}
    dump("data/reports/m10-summary.json", summary)

    (ROOT / "docs/CURRENT_MILESTONE.md").write_text("""# Current milestone\n\n## M10 — Pilot Reconstruction Batch and Throughput Validation\n\nStatus: **PASS** as of 2026-09-14.\n\nFive additional real buildings were selected from 29 candidates, passed bounded evidence preflight, built in two waves, validated as standalone GLBs, registered with LOD2 retained, and integrated into the pilot. Wave A passed the Central Square, W Global, generic fixture, metadata, and GLB regression gate before Wave B.\n\nThe pilot now contains seven approved LOD1 buildings at 23,796 triangles and 76 observed overview draw calls. The non-rectilinear test passed on C1 using its verified geographic polygon and shared edge-local facade mapping.\n\n## Explicit non-goals\n\n- no whole-BGC or complete-pilot reconstruction;\n- no LOD0, interiors, traffic, NPCs, final UI, or full spatial streaming;\n- no unsupported photorealism or arbitrary landmark polishing;\n- no Astra use.\n\n## Recommended next milestone\n\n**M11 — Evidence Coverage Expansion and Reconstruction Throughput**, using SOL for bounded architectural interpretation and Terra/Luna-suitable deterministic validation.\n""", encoding="utf-8")
    (ROOT / "docs/M10_BATCH_SELECTION.md").write_text("""# M10 batch selection\n\nThe canonical pilot produced 29 eligible candidates after excluding Central Square and W Global Center. The complete, dimension-by-dimension evaluation is in `data/reports/m10-candidate-pool.json`; no aggregate score replaces the visible evidence, diversity, cost, and stress dimensions.\n\n| Wave | Entity | Archetype | Evidence | Selection rationale |\n|---|---|---|---|---|\n| A | bgc_building_0004 — One Maridien | PODIUM_TOWER | READY_WITH_GAPS | Explicit outline/part heights and owner identity; tower/podium stress. |\n| A | bgc_building_0015 — JY Campos Centre | OFFICE_BLOCK | READY_WITH_GAPS | Confirmed identity and distinctive evidence-backed facade screen. |\n| B | bgc_building_0005 — Verve Residences Tower 2 | PODIUM_TOWER | READY_WITH_GAPS | Tall residential repetition without schema changes. |\n| B | bgc_building_0027 — UNIQLO | LOW_RISE_RETAIL | READY_WITH_GAPS | Current four-storey street-facing retail contrast. |\n| B | bgc_building_0011 — C1 | IRREGULAR_FOOTPRINT | READY_WITH_GAPS | Ten-edge real polygon tests arbitrary facade edges. |\n\nNo target was deferred. C1 resolves the M9 non-rectilinear uncertainty for polygonal massing, while its weak facade evidence remains conservative. All media references are metadata-only and RESEARCH_ONLY.\n""", encoding="utf-8")
    (ROOT / "docs/M10_THROUGHPUT_REPORT.md").write_text(f"""# M10 throughput report\n\nM10 completed 5/5 targets in two waves. Average automated build plus five-camera render and GLB validation time was **{averages['build_and_qa_seconds']:.2f} s/building**. The batch reused one schema and one generic builder; all target variation is configuration.\n\nWave A passed after three QA framing iterations on its unusually tall/mid-rise pair. Wave B isolated one package failure: UNIQLO's OSM level-derived height omitted its source link. The corrected package passed on retry 1 without rebuilding the other two targets.\n\nAverage authoritative sources were **{averages['authoritative_sources']:.1f} per target**, with **{averages['usable_references']:.1f} usable references per target**; all visual media stayed research-only and no images were copied. Evidence wall-clock time was not instrumented and is explicitly null in the machine report rather than estimated.\n\nThe dominant bottleneck is rights-safe visual coverage, especially weak/rear sides. Modeling cost is low once the evidence package exists; QA camera framing is the main deterministic nuisance across height extremes. See `data/reports/m10-building-costs.json`.\n""", encoding="utf-8")
    (ROOT / "docs/M10_SCALING_ANALYSIS.md").write_text("""# M10 scaling analysis\n\nFive new LOD1 assets added 175,532 pilot bytes, 2,700 triangles, and 5 actual overview draw calls relative to M9. The resulting pilot is 1,208,880 bytes, 23,796 triangles, and 76 overview calls. Same-material facade components remain semantic in authoring and merge to one runtime mesh per target.\n\nThe observed M10 marginal cost is 35,106 bytes, 540 triangles, and 1 overview call per added building. A linear 31-detailed-building planning extrapolation is roughly 2.05 MB, 36.8k triangles, and 100 overview calls. This is planning evidence only; it assumes similar archetypes and no streaming/culling redesign.\n\nAt current scale, runtime geometry is low risk. Evidence fidelity and source coverage dominate. Full spatial streaming remains deferred.\n""", encoding="utf-8")
    (ROOT / "docs/M10_FRAMEWORK_REPORT.md").write_text("""# M10 framework report\n\nFramework status: **STABLE**. Schema 1.0 remained unchanged. Five targets use shared footprint extrusion, material families, evidence metadata, QA cameras, runtime merge/export, and GLB validation. `PolygonEdgeFrame` is the only new shared primitive; it maps normalized u/v regions onto any exterior polygon edge with winding-aware outward normals.\n\nWave A found one backwards-compatibility defect: the generic builder assumed every GeoJSON feature had a top-level `id`, while the legacy fixture stores it in `properties.id`. The fallback was added and the fixture then passed. Central Square visual/semantic regression, W Global rebuild, metadata transport, and all 34 pre-M10 tests passed. With five M10 tests, the final suite is 39 tests.\n\nThere are five target configurations and zero target-specific Python builders. The 232 semantic authoring meshes become 12 standalone runtime meshes. No GPU-instancing extension was justified: merging same-material edge bands is simpler at this scale.\n""", encoding="utf-8")
    (ROOT / "docs/M10_PERFORMANCE_REPORT.md").write_text("""# M10 performance report\n\nThe production Next.js build passes and the browser console has zero warnings/errors. Methodology matches M8/M9: 759×742 CSS viewport, Canvas DPR 1, 5 s warmup, 15 s requestAnimationFrame sampling, fixed cameras, same host/browser family. Windows reports a desktop devicePixelRatio of 1.25; the Three.js Canvas remains explicitly fixed to DPR 1.\n\nOverview: 165.84 mean, 163.93 median, 153.85 p1 FPS; 76 calls, 23,796 rendered triangles, 76 geometries, 0 textures. The lowest new-building mean is C1 at 165.36 FPS; the lowest new-building p1 is 140.85 FPS at One Maridien/JY Campos. FPS remains secondary to the measured scene costs. Full per-camera data is in `data/reports/m10-browser-benchmark.json`.\n""", encoding="utf-8")
    append_once("docs/RECONSTRUCTION_PLAYBOOK.md", "## M10 batch execution", """## M10 batch execution\n\n1. Run `python scripts/reconstruction/prepare_m10.py` to refresh candidate selection and packages.\n2. Validate/build Wave A with `python scripts/reconstruction/build_batch.py --wave A --stage full --continue-on-error`.\n3. Run established-building, generic-fixture, metadata, and GLB regressions.\n4. Only after the gate passes, run Wave B. Use `--entity-id ... --retry-count N` for isolated retries.\n5. Rebuild the registry-driven pilot, validate the GLB, publish the web manifest, and capture fixed-camera renderer statistics.\n\nBatch failures must retain target-level diagnostics. Package validation always precedes Blender. Research-only imagery remains remote metadata and never becomes a distributed texture.""")
    append_once("docs/MODELING_GUIDELINES.md", "## Arbitrary polygon facades", """## Arbitrary polygon facades\n\nUse the verified geographic polygon directly for irregular LOD1 massing. `PolygonEdgeFrame` derives edge start/end, length, angle, winding-aware outward normal, normalized u/v coordinates, vertical range, and depth. Keep edge regions separate in authoring; merge only explicit same-material groups for runtime. Validate winding, degenerate edges, tessellation, bounds, and re-imported GLB orientation. Never introduce irregular vertices from photographs alone.""")
    append_once("docs/ARCHITECTURE.md", "## M10 batch reconstruction", """## M10 batch reconstruction\n\n```text\nm10-batch.json -> package validation -> configured polygon builder -> per-target GLB validation -> asset registry -> registry-driven pilot import -> browser metrics\n```\n\nBatch execution isolates target failures and supports fail-fast, continue-on-error, and exact-target retries. Existing custom builders remain supported; configured M10 assets integrate from their already-optimized standalone GLBs. Canonical evidence remains outside Blender.""")
    append_once("docs/DECISIONS.md", "## 2026-09-14 — M10 configured polygon batch", """## 2026-09-14 — M10 configured polygon batch\n\nKeep reconstruction schema 1.0. Add one winding-aware polygon-edge facade primitive and express all five M10 targets as package configuration, with no target-specific Python builder. Preserve semantic edge components in authoring and merge each same-material band family for runtime. Integrate configured targets from validated standalone GLBs through the asset registry. Defer GPU instancing and streaming because measured pilot cost remains low.""")
    append_once("docs/RESEARCH_LOG.md", "## 2026-09-14 — M10 bounded batch evidence", """## 2026-09-14 — M10 bounded batch evidence\n\nM10 reused the immutable OSM pilot snapshot and existing owner/government records, then added metadata-only research references for One Maridien, Verve Residences, JY Campos Centre, UNIQLO BGC High Street, and BHS Central C1. Official/operator evidence confirmed identity and location; property/architect pages supplied visual massing and facade observations. All exterior media is RESEARCH_ONLY and no file was downloaded.\n\nTechnical checks used the OpenStreetMap Simple 3D Buildings guidance (outline is the identity/overall footprint; building parts describe differing physical sections and should not be double-rendered), Blender glTF documentation (custom properties export as extras), and Three.js WebGLRenderer documentation (`renderer.info.render.calls`, triangles, geometries, textures).\n\nC1 identity was upgraded to CONFIRMED from the official BGC district directory plus its mapped location. Its ten-edge OSM footprint is verified geographic data; facade band spacing remains a procedural approximation. JY Campos' geometric facade pattern is verified photographic evidence, while its exact module is not asserted. UNIQLO's four-storey state is supported by current operator/secondary evidence; its 12.8 m height remains an OSM-level-derived estimate.""")
    print("M10_FINALIZE: PASS reports=5 docs=8")


if __name__ == "__main__":
    main()
