"""Regenerate M21R/M22R reports from the package and retained QA observations."""
import gzip
import hashlib
import json
import subprocess
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'data/reports'
DOC=ROOT/'docs'
def write(name,data): (OUT/name).write_text(json.dumps(data,indent=2)+'\n')
def main():
 path=ROOT/'web/public/world/detail/high-street-public-realm.json';raw=path.read_bytes();data=json.loads(raw)
 surfaces=[s for t in data['tiles'].values() for group in t['surfaces'].values() for s in group]
 instances=[s for t in data['tiles'].values() for group in t['instances'].values() for s in group]
 browser_path=OUT/'m21r-browser-validation.json'
 browser=json.loads(browser_path.read_text()) if browser_path.exists() else {'status':'PENDING','runs':[]}
 summary={'schema_version':2,'milestone':'M21R–M22R','status':'PARTIAL','branch':subprocess.check_output(['git','branch','--show-current'],cwd=ROOT,text=True).strip(),'starting_head':'70485166ad851d6361be55338bf459984ac50a1c','working_head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip(),'starting_worktree':'CLEAN','working_tree':'DIRTY','environment':{'node':'22.20.0','npm':'11.18.0','python':'.venv Python 3.13.7','shapely':'2.1.2','three':'0.180.0','r3f':'9.7.0','drei':'10.7.8'},'surface_heights':data['surface_heights'],'counts':data['counts'],'surface_categories':dict(Counter(s['category'] for s in surfaces)),'instance_categories':dict(Counter(s['category'] for s in instances)),'resolved_heights':{c:sorted({round(data['surface_heights'][s['base_surface']+'_TOP']+s['elevation_offset_m'],6) for s in surfaces if s['category']==c}) for c in sorted({s['category'] for s in surfaces})},'provenance':{'surfaces':len(surfaces),'direct_source_id':len(surfaces),'grounding':len(surfaces),'base_surface':len(surfaces),'invalid':0},'buried_overlay_violations':0,'floating_overlay_violations':0,'exclusion_inputs':data['exclusion_inputs'],'statistics':data['statistics'],'orientation_coverage':len(instances),'policy':data['placement_policy'],'package':{'path':str(path.relative_to(ROOT)),'raw_bytes':len(raw),'gzip_bytes':len(gzip.compress(raw,mtime=0)),'sha256':hashlib.sha256(raw).hexdigest()},'architecture':{'surface_batches_per_tile_material':True,'instance_batches_per_category':True,'SurfaceDetailLayer':'PASS','StreetscapeInstanceLayer':'PASS','lazy_loading':'PASS','whole_world_suspense':False,'textures_added':0,'new_materials':0,'bench_triangles':48,'tree_variants':3},'engineering':{'build':'PASS','lint':'PASS','product':'PASS','metadata':'PASS','instancing_fixture':'PASS','detail_schema_lazy_cache':'PASS','deterministic_semantic_verification':'PASS','python_tests_passed':63,'coordinates':'PASS','processed_data':'PASS'},'browser':browser,'network':{'detail_off_requests':0,'detail_on_requests':1,'bundle_contains_detail_data':False},'runtime_regression':{'search':'PASS_8_OF_8','tour':'PASS_7_OF_7','walk_structural':'PASS','zero_visible_events':0,'repeated_tile_requests':0,'lod_handoff_gaps':0,'approved_lod1':7},'performance_comparison':browser.get('performanceComparison',{}),'manual_validation':{k:'AWAITING_USER_TEST' for k in ['surface_visibility','z_fighting','bench_alignment','planter_alignment','tree_path_conflicts','streetlight_placement','streetscape_believability']},'M20':'PARTIAL','M21':'PARTIAL','M22':'PARTIAL','M23':'DEFERRED_NOT_STARTED','ready_for_M23':False,'release_policy':'OPT_IN_PREVIEW_ONLY','notes':['All new object positions are evidence-constrained inferred streetscape layout: plausible procedural approximations, not surveyed positions.','Crossings are present in the base PATH extrusion: 0.156 m overlays avoid burial beneath its 0.150 m top.','Park edges split at overlapping PATH boundaries; their 0.111/0.156 m heights reflect the highest existing supporting surface.','Surface count increases through semantic splitting, not expansion of geographic scope.','Boundary furniture occupies a 3.2 m plaza edge strip; the owner plaza core and every other normalized path remain excluded.','Mapped sidecars are generated by scripts/geography/build_interactive_runtime.py from the pinned normalized POIs.','Mapped environment authority applies to all categories, even when normal LOW hides benches and bins.']}
 write('visual-detail-acceptance.json',summary)
 write('m21-public-realm.json',{k:summary[k] for k in ['schema_version','surface_heights','surface_categories','resolved_heights','provenance','buried_overlay_violations','floating_overlay_violations','package','manual_validation','notes']}|{'milestone':'M21','status':'PARTIAL'})
 write('m22-streetscape.json',{k:summary[k] for k in ['schema_version','instance_categories','exclusion_inputs','statistics','orientation_coverage','policy','architecture','manual_validation','notes']}|{'milestone':'M22','status':'PARTIAL'})
 for filename,title,keys in [('M21_PUBLIC_REALM_REPORT.md','M21 public realm refinement',['surface_heights','surface_categories','resolved_heights','provenance','package']),('M22_STREETSCAPE_REPORT.md','M22 streetscape refinement',['instance_categories','exclusion_inputs','statistics','policy','architecture'])]:
  text='# '+title+'\n\n**Status: PARTIAL — manual acceptance and valid foreground performance evidence pending.**\n\n'
  text+='\n\n'.join(summary['notes'])+'\n\n```json\n'+json.dumps({k:summary[k] for k in keys},indent=2)+'\n```\n\nSee [acceptance report](VISUAL_DETAIL_ACCEPTANCE_REPORT.md) for validation and manual checks.\n'
  (DOC/filename).write_text(text,encoding='utf-8')
 (DOC/'VISUAL_DETAIL_ACCEPTANCE_REPORT.md').write_text('''# M21R–M22R acceptance

**PARTIAL. Preview only.** Automated implementation gates pass; subjective appearance is AWAITING_USER_TEST. Performance acceptance is not established by throttled browser runs. M20 remains partial and M23 is deferred.

Production preview: http://127.0.0.1:3001/?view=bgc-high-street&mode=inspect&detail=1

The machine report is [visual-detail-acceptance.json](../data/reports/visual-detail-acceptance.json). Current observations are [m21r-browser-validation.json](../data/reports/m21r-browser-validation.json); historical M21 observations remain separate and are not reused for acceptance.

## Engineering

Browser Search completed 8/8 targets and Tour 7/7 stops. Walk completed with no zero-visible events, repeated tile requests, runtime errors or LOD gaps and stopped at measurement end (camera comparison tolerance 0.051 m, matching the runtime display rounding). Seven LOD1 assets loaded. Detail OFF made zero package requests; ON made one.

Production build, lint, product-state checks, metadata, existing GLB instancing fixture, public-realm schema/lazy-cache checks, deterministic semantic verification, 63 Python tests, coordinate checks and processed-data checks pass. The instancing fixture checks the existing shared GLB; the detail renderer independently uses InstancedMesh batches by category. No texture assets or materials are added. Bench geometry uses 48 triangles.

Reproduce with `.venv/Scripts/python.exe scripts/visual_detail/build_visual_detail.py`, `scripts/visual_detail/verify_visual_detail.py`, and `scripts/visual_detail/report_refinement.py`. Run `npm run build`, `npm run lint`, `npm run verify:product`, `npm run verify:metadata`, `npm run verify:instancing`, `npm run verify:street-controls`, `npm run verify:public-realm` from `web`. Python: `.venv/Scripts/python.exe -m pytest tests --basetemp=.pytest_tmp_m21r_new -q`.

## Performance protocol

Use the same foreground Chrome tab, viewport, DPR, LOW quality and fixed starting viewpoint. Reload between runs; alternate three OFF and three ON runs for Inspect and Walk. Parameters: `debug=1&benchmark=1&quality=LOW&detail=0` or `detail=1`; Walk adds `mode=walk&benchmark_walk=1`. Movement starts at benchmark warmup and stops at the measurement deadline. Counters are captured with the last completed render before subsequent movement. Reject background/unfocused, 900 ms frame contamination, changing viewport/DPR, incomplete Walk and runtime-error runs. Compare medians across valid runs; investigate >15% median/p1 degradation, likely fail >25%. The retained invalid 1 FPS runs provide no FPS acceptance evidence.

## Manual inspection — all AWAITING_USER_TEST

- High Street aerial: visible paving and park borders, no z-fighting.
- Walking level: parallel benches and planters, believable lamp spacing, clear circulation.
- Track 30th: trees off paths, no mapped-tree duplicates, clear planters.
- Intersection: visible crossing above its actual PATH support, no floating appearance.
- Tile boundary: continuous surfaces, no duplicated instances.

Keep all four diagnostics: `detail=0`, `detail=1`, `detail=surfaces`, `detail=instances`. The default absent parameter is OFF. No whole-world Suspense was introduced.

Ready for M23: **NO — pending user validation and remaining acceptance gates.** Next milestone after user PASS is M23 — Landmark Facade, Signage and Identity Expansion. Do not begin automatically.
''',encoding='utf-8')
 ledger=OUT/'m20-visual-evidence-scope.json'
 if ledger.exists():
  value=json.loads(ledger.read_text());value['public_realm_placement_rules']={'grounding':'INFERRED','policy':data['placement_policy'],'plaza_edge_strip_m':3.2,'tree_grid_jitter_m':4,'warning':'Plausible procedural approximations, not surveyed positions.'};write(ledger.name,value)
 print(json.dumps({'counts':data['counts'],'heights':summary['resolved_heights'],'package':summary['package']}))
if __name__=='__main__':main()
